### ISSUE TITLE
OAuth credentials for Github in Coveralls configuration are no longer valid

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1829]
Source Not Available
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

https://coveralls.io/builds/14631149/source?filename=adam-core%2Fsrc%2Fmain%2Fscala%2Forg%2Fbdgenomics%2Fadam%2Frdd%2FADAMContext.scala

Reported by @ffinfo on Gitter, thanks!

**Comment by fnothaft** [comment]
I believe this is fixed now. Closing.

**Comment by heuermh** [comment]
I'm still seeing this now

Source Not Available

The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

https://coveralls.io/builds/15296027/source?filename=adam-core%2Fsrc%2Fmain%2Fscala%2Forg%2Fbdgenomics%2Fadam%2Frdd%2FADAMContext.scala#L1721
